version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: crm_postgres
    environment:
      POSTGRES_DB: crm_demo
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_demo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
